CREATE TABLE pessoa (
	pes_codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pes_razao varchar(100),
	pes_fantasia varchar(100),
	pes_telefone varchar(16),
	pes_cpfcnpj varchar(16),
	pes_ierg varchar(16),	
	pes_observacao varchar(500),
	pes_tipo_pessoa integer	
);
comment on column pessoa.pes_tipo_pessoa is '1 = CLIENTES, 2 = FORNECEDORES, 3 = FUNCIONARIOS';

SELECT * FROM pessoa;
DELETE FROM pessoa;

INSERT INTO pessoa (
	pes_razao, pes_fantasia, pes_telefone, pes_cpfcnpj, pes_ierg, pes_observacao, pes_tipo_pessoa
) VALUES (
	'CLIENTE A VISTA', 'VISTA', '(00) 0000-0000', '000.000.000-00', NULL, NULL, 1
);

INSERT INTO pessoa (
	pes_razao, pes_fantasia, pes_telefone, pes_cpfcnpj, pes_ierg, pes_observacao, pes_tipo_pessoa
) VALUES (
	'CLIENTE CARTÃO', 'CARTÃO', '(00) 0000-0000', '000.000.000-00', NULL, NULL, 1
);

INSERT INTO pessoa (
	pes_razao, pes_fantasia, pes_telefone, pes_cpfcnpj, pes_ierg, pes_observacao, pes_tipo_pessoa
) VALUES (
	'CLIENTE PIX', 'PIX', '(00) 0000-0000', '000.000.000-00', NULL, NULL, 1
);