CREATE TABLE produto (
	prd_codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prd_nome_completo varchar(100),
	prd_nome_popular varchar(100),
	prd_codigo_barra varchar(100),
	prd_referencia varchar(100),
	prf_ncm varchar(10),
	prd_grupo integer,
	prd_subgrupo integer
);

CREATE TABLE situacao_tributaria (
	sit_codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sit_descricao varchar(100),
	sit_cst integer	
);

CREATE TABLE produto_filial (
	prf_codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prf_codigo_prd integer,
	prf_filial integer,
	prf_custoini NUMERIC(15, 2),
	prf_vendavista NUMERIC(15, 2),
	prf_vendaprazao NUMERIC(15, 2),
	prf_situacao_tributaria integer,
	constraint fk_prf_filial foreign key (prf_filial) references filial(fil_codigo),
	constraint fk_prf_prd foreign key (prf_codigo_prd) references produto(prd_codigo),
	constraint fk_prf_sit_tribut foreign key (prf_situacao_tributaria) references situacao_tributaria(sit_codigo)
);


INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 00', 00);
INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 20', 20);
INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 40', 40);
INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 60', 60);
INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 102', 102);
INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 500', 500);
INSERT INTO situacao_tributaria (sit_descricao, sit_cst) VALUES ('PRODUTOS 900', 900);

INSERT INTO PRODUTO (prd_nome_completo, prd_nome_popular, prd_codigo_barra, prd_referencia, prf_ncm, prd_grupo, prd_subgrupo) VALUES ('ARROZ PARBOLIZADO', 'ARROZ', 112233, 'REF. 1', 1, 1, 10061091);
INSERT INTO PRODUTO (prd_nome_completo, prd_nome_popular, prd_codigo_barra, prd_referencia, prf_ncm, prd_grupo, prd_subgrupo) VALUES ('FEIJÃO', 'FEIJÃO', 445566, 'REF. 2', 1, 1, 00000000);
INSERT INTO PRODUTO (prd_nome_completo, prd_nome_popular, prd_codigo_barra, prd_referencia, prf_ncm, prd_grupo, prd_subgrupo) VALUES ('TRIGO', 'TRIGO', 778899, 'REF. 3', 1, 1, 00000000);
INSERT INTO PRODUTO (prd_nome_completo, prd_nome_popular, prd_codigo_barra, prd_referencia, prf_ncm, prd_grupo, prd_subgrupo) VALUES ('MILHO', 'MILHO', 154678, 'REF. 4', 1, 1, 00000000);

INSERT INTO produto_filial (prf_codigo_prd, prf_filial, prf_custoini, prf_vendavista, prf_vendaprazao, prf_situacao_tributaria) VALUES (1, 1, 10, 25, 27, 5);
INSERT INTO produto_filial (prf_codigo_prd, prf_filial, prf_custoini, prf_vendavista, prf_vendaprazao, prf_situacao_tributaria) VALUES (1, 2, 11, 26, 28, 1);